# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: amd64,arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew dist
      env:
        USERNAME: ${{ secrets.GH_USERNAME }}
        TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: print build dir
      run: 'ls -lah build/libs'

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: casmith/marvinbot:latest
        platforms: linux/amd64,linux/arm64

#    - name: "Deploy"
#      uses: GoldenspearLLC/build-jenkins-job@master
#      with:
#        jenkins-url: ${{ secrets.JENKINS_URL }}
#        jenkins-token: ${{ secrets.JENKINS_TOKEN }}
#        user: ${{ secrets.JENKINS_USERNAME }}
#        job-path: "job/deploy/job/master"
#        job-params: '{"component": "marvin"}'
